### ISSUE TITLE
fillParent dont work

### ISSUE THREAD

**Issue by AlvaroEstrada** [ChathuraHettiarachchi/CSnackBar#4]
Hello!

I am having problems using a custom view. It does not allow me to use "fillParent" and the settings like color or alignment do not work for me either.

My xml code:

```
> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
>                 android:id="@+id/custom_upload_snackbar"
>                 android:layout_width="match_parent"
>                 android:layout_height="48dp"
>                 android:orientation="horizontal"
>                 android:background="@drawable/transparent_background"
>                 >
>         <ProgressBar
>             android:id="@+id/snackbar_progressBar"
>             style="?android:attr/progressBarStyle"
>             android:layout_width="25dp"
>             android:layout_height="25dp"
>             android:layout_marginEnd="15dp"
>             android:layout_gravity="center_vertical"
>             android:progressTint="@color/colorPrimary"
>             />
>         <TextView
>             android:id="@+id/snackbar_text"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:gravity="center_vertical"
>             android:layout_gravity="center_vertical"
>             android:textColor="@color/colorPrimary"
>             />
> 
>             </LinearLayout>
```

My Java code:

       `Snackbar snack = new Snackbar();
        View view = LayoutInflater.from(this).inflate(R.layout.custom_upload_snackbar, null);
        TextView tv = (TextView) view.findViewById(R.id.snackbar_text);
        ProgressBar prBar = (ProgressBar) view.findViewById(R.id.snackbar_progressBar);

        tv.setText(R.string.fragment_document_uploading);

        snack.with(this,null)
                .type(Type.CUSTOM, 0xff323232)
                .fillParent(true)
                .contentView(view, 48)
                .textAlign(Align.CENTER)
                .duration(Duration.INFINITE)
                .show();`

How can i fix this?

Im use minSDK 21 and Landscape on tablet.

Thanks.

**Comment by ChathuraHettiarachchi** [comment]
@AlvaroEstrada I have found an issue with the library. To make Snackbar fill tablet's width, please use RelativeLayout instead of LinearLayout. It will fix the issue. Sorry for the inconvenience. I'll update the library soon. If you need to Align text center and you are using a custom view, you need to center it in the custom view.

**Comment by AlvaroEstrada** [comment]
First of all thank you for the answer and your library. I find it wonderful and easy to use.

However, I have to tell you that with RelativeLayout it does not work either :(

**Comment by ChathuraHettiarachchi** [comment]
@AlvaroEstrada Can you share a screenshot, that would be helpful.

**Comment by AlvaroEstrada** [comment]
The first snackbar with progressbar I use to upload a file. As you see, it does not respect the fillParent.

![screenshot_20180620-125105](https://user-images.githubusercontent.com/6849710/41654206-fb97a634-7488-11e8-9b68-ca7cb2377cfe.png)

> XML File:

        <?xml version="1.0" encoding="utf-8"?>
        <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:id="@+id/custom_upload_snackbar"
             android:layout_width="fill_parent"
             android:layout_height="fill_parent"
         >
        
        <ProgressBar
            android:id="@+id/snackbar_progressBar"
            style="?android:attr/progressBarStyle"
            android:layout_width="25dp"
            android:layout_height="25dp"
            android:layout_gravity="center_vertical"
            android:progressTint="@color/colorPrimary"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_alignParentStart="true"
            android:layout_centerInParent="true"
            />

        <TextView
            android:id="@+id/snackbar_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            android:layout_gravity="center_vertical"
            android:textColor="@color/colorPrimary"
            android:layout_alignParentStart="true"
            android:layout_centerInParent="true"
            android:layout_marginStart="48dp"
            android:layout_marginEnd="16dp"
            />
      </RelativeLayout>

> Java Code:

    public static void loadUploadSnackbar(int value){

        Snackbar snack = new Snackbar();

        View view = LayoutInflater.from(activity).inflate(R.layout.custom_upload_snackbar, null);

        TextView tv = (TextView) view.findViewById(R.id.snackbar_text);

        switch (value){
            case 0:
                tv.setText(R.string.fragment_document_uploading);
                break;
            case 1:
                tv.setText(R.string.fragment_document_uploading_multi);
                break;
          }

        snack.with(activity,null)
                .type(Type.CUSTOM, 0xff323232)
                .fillParent(true)
                .contentView(view, 48)
                .duration(Duration.INFINITE)
                .show();
    }


The second snackbar in green I use to notify that it has been successfully uploaded. As it does not have a custom view, it respects the fillParent perfectly.

![screenshot_20180620-125134](https://user-images.githubusercontent.com/6849710/41654218-058ad062-7489-11e8-99b8-887f574f6be2.png)

> Java Code:

```
  public static void loadDoneUploadSnackbar(){
        Snackbar.with(activity,null)
                .type(Type.SUCCESS)
                .textAlign(Align.CENTER)
                .message(activity.getResources().getString(R.string.fragment_document_upload_ok))
                .duration(Duration.LONG)
                .fillParent(true)
                .show();
    }
```

**Comment by ChathuraHettiarachchi** [comment]
@AlvaroEstrada Could you replace you xml with the following and try. Let me know if the error staying.
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="48dp"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ProgressBar
            android:id="@+id/snackbar_progressBar"
            style="?android:attr/progressBarStyle"
            android:layout_width="25dp"
            android:layout_height="25dp"
            android:layout_alignParentLeft="true"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="16dp"
            android:layout_marginStart="16dp"
            android:progressTint="@color/colorPrimary" />

        <TextView
            android:id="@+id/snackbar_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:layout_toEndOf="@+id/snackbar_progressBar"
            android:layout_toRightOf="@+id/snackbar_progressBar"
            android:gravity="center_vertical"
            android:textColor="@color/colorPrimary" />

    </RelativeLayout>
</RelativeLayout>`

**Comment by ChathuraHettiarachchi** [comment]
@AlvaroEstrada Could you replace you xml with the following and try. Let me know if the error staying.

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="48dp"
    android:orientation="vertical">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <ProgressBar
            android:id="@+id/snackbar_progressBar"
            style="?android:attr/progressBarStyle"
            android:layout_width="25dp"
            android:layout_height="25dp"
            android:layout_alignParentLeft="true"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="16dp"
            android:layout_marginStart="16dp"
            android:progressTint="@color/colorPrimary" />

        <TextView
            android:id="@+id/snackbar_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:layout_toEndOf="@+id/snackbar_progressBar"
            android:layout_toRightOf="@+id/snackbar_progressBar"
            android:gravity="center_vertical"
            android:textColor="@color/colorPrimary" />
    </RelativeLayout>
</RelativeLayout>

If the error fixed let me know that too. 
Thanks,

**Comment by ChathuraHettiarachchi** [comment]
@AlvaroEstrada Could you replace you xml with the following and try. Let me know if the error staying.

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="48dp"
    android:orientation="vertical">
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <ProgressBar
            android:id="@+id/snackbar_progressBar"
            style="?android:attr/progressBarStyle"
            android:layout_width="25dp"
            android:layout_height="25dp"
            android:layout_alignParentLeft="true"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="16dp"
            android:layout_marginStart="16dp"
            android:progressTint="@color/colorPrimary" />

        <TextView
            android:id="@+id/snackbar_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_gravity="center_vertical"
            android:layout_toEndOf="@+id/snackbar_progressBar"
            android:layout_toRightOf="@+id/snackbar_progressBar"
            android:gravity="center_vertical"
            android:textColor="@color/colorPrimary" />
    </RelativeLayout>
</RelativeLayout>
```

If the error fixed let me know that too. 
Thanks,

**Comment by AlvaroEstrada** [comment]
Thank you very much Choota.

Right now I'm out of work and I do not have access to the project.

Tomorrow first thing I try it and I tell you the results.

Thanks, again :)

**Comment by AlvaroEstrada** [comment]
Hi again Choota!

I have tested your changes and they work perfectly!

I modified the code to center the text and adapt it to future versions of android substituting the layout_marginRight for layout_marginEnd etc.

But with the structure that you have provided to me now it does occupy the full width.

Many thanks!!!

> Here the code:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="48dp"
    android:orientation="vertical">
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
                <ProgressBar
                    android:id="@+id/snackbar_progressBar"
                    style="?android:attr/progressBarStyle"
                    android:layout_width="25dp"
                    android:layout_height="25dp"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center_vertical"
                    android:layout_marginEnd="16dp"
                    android:layout_marginStart="16dp"
                    android:layout_toStartOf="@+id/snackbar_text"
                    android:progressTint="@color/colorPrimary" />

                <TextView
                    android:id="@+id/snackbar_text"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:layout_gravity="center_vertical"
                    android:gravity="center_vertical"
                    android:textColor="@color/colorPrimary" />
        </RelativeLayout>
</RelativeLayout>

```
