### ISSUE TITLE
Custom view Button onClick()

### ISSUE THREAD

**Issue by mechaadi** [ChathuraHettiarachchi/CSnackBar#6]
Hey, I am trying to setOnClickListener on a button of custom_view, but it crashes with a nullPointerException. Any ideas?

**Comment by mechaadi** [comment]
oh..ok i got this.

 View view = getLayoutInflater().inflate(R.layout.custom_view, null);
        btn = (Button)view.findViewById(R.id.snackButton);

Great library

**Comment by ChathuraHettiarachchi** [comment]
@mechaadi Thank you for using my library. Feel free to update
